function cam_calibration_loadimages_Callback(~, ~, ~)
[cam_selected_target_images,location]=uigetfile(...
    {'*.bmp;*.tif;*.tiff;*.jpg;*.png','Image files';
   '*.bmp','Bitmaps'; ...
   '*.tif;*.tiff','TIF'; ...
   '*.jpg','JPEG'; ...
   '*.png','PNG'; ...
   '*.*',  'All Files'}...
    ,"MultiSelect","on",'Select images of the calibration target',gui.retr('pathname'));
if ~isempty(cam_selected_target_images)
    pathfiles=fullfile(location,cam_selected_target_images);
    gui.put('cam_selected_target_images',pathfiles)
end