function str = wtbxfileheader(varargin)
%WTBXFILEHEADER Utility for generating a file header
%   WTBXFILEHEADER Generates a file header with no custom annotations for
%   the signal processing toolbox using '%' as the commenting character.
%
%   WTBXFILEHEADER(DESC) Generates a file header and adds the description
%   DESC before the toolbox information.  If DESC is less than 10
%   characters it will be on the same line as the toolbox information.
%
%   WTBXFILEHEADER(DESC, TBX) Generates a file header for the toolbox
%   specified in the string TBX.
%
%   WTBXFILEHEADER(DESC, TBX, COM) Generates a file header using the
%   COM as the commenting character.
%
%   WTBXFILEHEADER(DESC, TBX, COM, DATEFORM) Generates a file header using
%   the specified DATEFORM.  See DATESTR for more information.  DATEFORM is
%   dd-MMM-yyyy hh:mm:ss by default.
%
%   If DESC or TBX is '', the defaults will be used.

%   Copyright 1988-2020 The MathWorks, Inc.

desc     = '';
tbx      = 'wavelet';
comment  = '%';
dateform = 'dd-MMM-yyyy hh:mm:ss';

if ~isempty(varargin)
    if isnumeric(varargin{end})
        dateform      = varargin{end};
        varargin(end) = [];
    end
end
if ~isempty(varargin)
    desc = varargin{1};
end
if length(varargin) > 1
    tbx = varargin{2};
end
if length(varargin) > 2
    comment = varargin{3};
end

% Get the toolbox info which includes the name and version.
minfo = ver('matlab');
tinfo = ver(tbx);
tinfo = tinfo(1); % In case there are multiple toolboxes on the path.

% If the description is short and does not end with a '.' we want to
% attach it to the 'generated by' line.  Otherwise it goes on its own line.
if isempty(desc)
    descStr=desc;
    str1 = sprintf('Generated by MATLAB(R) %s and %s %s.', ...
        minfo.Version, tinfo.Name, tinfo.Version);
elseif length(desc) < 10 && desc(end) ~= '.'
    descStr = '';
    str1 = sprintf('%s generated by MATLAB(R) %s and the %s %s.',...
        desc, minfo.Version, tinfo.Name, tinfo.Version);
else
    descStr = sprintf(' %s\n%s', desc,comment);
    str1 = sprintf('Generated by MATLAB(R) %s and the %s %s.', ...
        minfo.Version, tinfo.Name, tinfo.Version);
end

str2 = sprintf('%s Generated on: %s', comment, ...
    char(datetime('now','Format',dateform)));

str = sprintf('%s%s %s\n%s', comment, descStr, str1, str2);
