function aboutpiv_Callback(~, ~, ~)
string={...
	'PIVlab - Time-Resolved Digital Particle Image Velocimetry Tool for MATLAB';...
	['version: ' gui.gui_retr('PIVver')];...
	'';...
	'developed by Dr. William Thielicke and Prof. Dr. Eize J. Stamhuis';...
	'published under the MIT licence.';...
	'';...
	'';...
	'first released March 09, 2010';...
	'';...
	'http://PIVlab.blogspot.com';...
	'contact: PIVlab@gmx.com';...
	'';...
	'The development happened mostly in Williams free time.';...
	'But since he is now working for a company developing PIV equipment,';...
	'some of his work time is dedicated to improving PIVlab. Therefore,';...
	'the development is partly sponsored by www.OPTOLUTION.com.';

	};
helpdlg(string,'About')

