function MainWindow_CloseRequestFcn(hObject, ~, ~)
handles=gui.gethand;
batchModeActive=gui.retr('batchModeActive');
yes_synonyms = { ...
    'Absolutely', ...
    'Definitely', ...
    'Yes', ...
    'Of course', ...
    'Certainly', ...
    'Indeed', ...
    'Sure thing', ...
    'Right', ...
    'Yup', ...
    'Yep', ...
    'Yeah', ...
    'Aye', ...
    'You bet', ...
    'For sure', ...
    'Roger that', ...
    'Heck yeah', ...
    'Yes please', ...
    'Claro!', ...
    };
yes=yes_synonyms{randi(numel(yes_synonyms))};
no_synonyms = { ...
    'Nope', ...
    'No', ...
    'Nah', ...
    'No way', ...
    'Negative', ...
    'Never', ...
    'Not really', ...
    'Absolutely not', ...
    'By no means', ...
    'No, thank you', ...
    'Not today', ...
    'Probably not', ...
    'No thanks', ...
    'I think not', ...
    };
no=no_synonyms{randi(numel(no_synonyms))};

if batchModeActive == 0
    figure(hObject);drawnow
    button=gui.custom_msgbox('quest',getappdata(0,'hgui'),'Quit?','Do you want to quit PIVlab?','modal',{yes no},no);
else
    button = yes;
end
try
    gui.toolsavailable(1)
catch
end
if strcmp(button,yes)==1
    try
        gui.set_preference('homedir',gui.retr('homedir'));
        gui.set_preference('pathname',gui.retr('pathname'));
        gui.store_last_acquisition_settings %image acquisition panel for the next start
    catch
    end
    try
        PIVlab_capture_lensctrl (1400,1400,0) %lens needs to be set to neutral otherwise re-enabling power might cause issues
    catch
    end
    try
        hgui = getappdata(0,'hgui');
        serpo=getappdata(hgui,'serpo');
        string3='WarningSignDisable!';
        pause(1)
        writeline(serpo,string3); %disable the lighting of the laser warning sign
        pause(0.5)
    catch
    end
    try
        second_monitor_fig = gui.retr('second_monitor_fig');
        if ~isempty(second_monitor_fig) && isvalid(second_monitor_fig)
            delete(second_monitor_fig);
        end
    catch
    end
    try
        delete(hObject);
    catch
        close(gcf,'force');
    end
end