function s = base_settings()
%BASE_SETTINGS Complete API settings struct with built-in values.
%   pivlab.defaults overwrites these values with the defaults of the PIVlab GUI
%   (gui.default_settings). The values here are only used for API settings without a GUI control.

s.preprocess = struct( ...
    'CLAHE', true, 'CLAHESize', 64, ...
    'Highpass', false, 'HighpassSize', 15, ...
    'IntensityCapping', false, ...
    'Wiener', false, 'WienerSize', 3, ...
    'AutoLimit', true, 'MinIntensity', 0, 'MaxIntensity', 1, ...
    'Background', "none", ...
    'Roi', [], ...
    'Mask', []);

s.analysis = struct( ...
    'Algorithm', "fft", ...
    'InterrogationArea', 64, 'Step', 32, ...
    'Passes', 2, 'PassSizes', [32 32 32], ...
    'SubpixelFinder', "gauss3point", ...
    'DisableAutocorrelation', false, ...
    'Robustness', "standard", ...
    'RepeatLastPass', false, 'RepeatLastPassThreshold', 0.025, ...
    'Uncertainty', false, ...
    'OFVSmoothness', 40, 'OFVPyramidLevels', 5, 'OFVMedianFilter', "off", ...
    'Parallel', false);

s.filter = struct( ...
    'StdevCheck', true, 'StdevThreshold', 8, ...
    'LocalMedian', true, 'LocalMedianThreshold', 3, ...
    'VelocityLimits', [], ...
    'CorrelationFilter', false, 'CorrelationThreshold', 0.5, ...
    'NotchFilter', false, 'NotchLimits', [-1 1], ...
    'ContrastFilter', false, 'ContrastThreshold', 0, ...
    'BrightnessFilter', false, 'BrightnessThreshold', 1, ...
    'LimitUnits', "result", ...
    'Interpolate', true);

s.calibration = struct( ...
    'calxy', 1, 'calu', 1, 'calv', 1, ...
    'offset_x_true', 0, 'offset_y_true', 0, ...
    'x_axis_direction', 1, 'y_axis_direction', 1, ...
    'realdist', 1, 'time_inp', 1, 'pointscali', [], ...
    'displacement_only', false);

s.derive = struct( ...
    'Smoothing', "none", 'SmoothingStrength', 0.3, 'TemporalWindow', 3);

s.display = struct( ...
    'Colormap', "parula", 'ColormapSteps', 256, 'MapInterpolation', "bilinear", ...
    'VectorScale', "auto", 'VectorSkip', 1, 'EnhanceImage', false);
end
