function [img, features, points_obj] = image_feature_extraction(img)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
    img = imadjust(img);
    img = imflatfield(img, 200);
    img = imgaussfilt(img, 5);
    features = detectMSERFeatures(...
        img, ...
        ThresholdDelta=10,...
        RegionAreaRange=[800, 1e6],...
        MaxAreaVariation=40 ...
    );
    [features, points_obj] = extractFeatures(img, features);
end