function c = get_roi_constraints(camera_type, max_cam_res)
switch camera_type
	case 'OPTRONIS'
		c = struct('step_x',32, 'step_y',2,  'step_w',64, 'step_h',4, ...
		           'min_w',256, 'min_h',4, ...
		           'sensor_w',max_cam_res(1), 'sensor_h',max_cam_res(2));
	case 'pco_edge26'
		c = struct('step_x',32, 'step_y',32, 'step_w',32, 'step_h',8, ...
		           'min_w',32,  'min_h',8, ...
		           'sensor_w',max_cam_res(1), 'sensor_h',max_cam_res(2));
	case 'OPTOcam_20_9'
		%ROI is in binned pixels. Minimum width scales with binning (measured: 304 at binning 2, 152 at 4).
		binning = gui.retr('binning');
		if isempty(binning)
			binning = 1;
		end
		c = struct('step_x',8,  'step_y',8,  'step_w',8,  'step_h',8, ...
		           'min_w',608/binning, 'min_h',16, ...
		           'sensor_w',max_cam_res(1)/binning, 'sensor_h',max_cam_res(2)/binning);
	otherwise
		c = struct('step_x',8,  'step_y',2,  'step_w',8,  'step_h',2, ...
		           'min_w',8,   'min_h',2, ...
		           'sensor_w',max_cam_res(1), 'sensor_h',max_cam_res(2));
end
